spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/reservationsys?serverTimezone=Asia/Seoul
    username: root
    password: 1234
  jpa:  #hibernate > ???? entity? ??? db? table? ?????
    properties:
      hibernate:
        format_sql:true
    show-sql: true
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    baseline-on-migrate: true
    url: jdbc:mysql://localhost:3306/reservationsys?serverTimezone=UTC&characterEncoding=UTF-8
    user: root
    password: 1234
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
